### PR TITLE
Enhance all the things! :)

### PR DESCRIPTION
**Pull request by karlp**
A series of commits, pulled from both @pablomarx as well as my own code, that does...

* simplifies adding new parts
* Adds newer bootloader support
* Adds support for (verified) ch32v307

I've tried to split these commits as well as possible, but I do realize this is a wide ranging commit.  The commits from @pablomarx I've taken at face value, but without them, my ch32v307 with bootloader v2.60 didn't work.

Unfortunately I have _not_ explicitly tested this with any of the more "traditional" parts (yet)  I simply don't have enough test devices for that.

### CODE REVIEW

**Comment by karlp** [comment]
I like some of the refactoring that was done in #21, but it does allll of it in a single big commit, so it's hard to pull in pieces of it.  I've tried to make less structural changes up front while expanding functionality, though some structural overhauls do feel in order to grow this moving forward.  Thanks so much for having this base line functionality "just working" though!

**Comment by pablomarx** [comment]
For what its worth, for my changes that were incorporated into this, I had successfully tested them on the following devices:

* CH32V103C8 BTVER 02.60
* CH32V103R8 BTVER 02.60
* CH571F BTVER 02.80
* CH573F BTVER 02.70
* CH579F BTVER 02.70
* CH579M BTVER 02.61
* CH582M BTVER 02.40

**Comment by karlp** [comment]
hrm, I failed to get ch582m btver 2.40 toprogram in my fork today, either with or without the dummy extra write.  I'll have to try your original code, see if that works for me and if I've got somethign wrong.

**Comment by pablomarx** [comment]
@karlp Is it failing on the first write, or does everything appear successful but the firmware doesn't execute?

If its failing after the first write, it may be because the "Enable sumilat interface" was enabled via WCH ISP Tool.

**Comment by pablomarx** [comment]
@karlp I think 2.4 needs the 8 byte checksum instead of 4 byte.  Changing that has made it able to flash my CH549F on BTVER 02.40.

**Comment by pablomarx** [comment]
USB traffic from a patched WCH ISP Tool programming a CH549F with BTVER 02.40:

```
# DETECT_CHIP_CMD_V2
>>> a1120049124d4355204953502026205743482e434e
<<< a10e02004912

# READ_CFG_CMD_V2
>>> a702001f00
<<< a70e1a001f00000000002000000000d2954e00020400bb4eb84400007393

# WRITE_CFG_CMD_V2
>>> a80e000700000000000000000000d20000
<<< a80e02000000

# READ_CFG_CMD_V2
>>> a702001f00
<<< a70e1a001f00000000002000000000d2954e00020400bb4eb84400007393

# SEND_KEY_CMD_V26
>>> a31e00000000000000000000000000000000000000000000000000000000000000
<<< a30e0200a100

# ERASE_CHIP_CMD_V2_32BIT
>>> a404003b000000
<<< a40e02000000

# WRITE_CMD_V2
# file: 00000000  02 06 e1 00 00 00 00 00  00 00 00 00 00 00 00 00  |..?.............|
>>> a53d000000000000090dea0b0b0b0b540b0b0b0b0b0b0b540b0b0b0b0b0b0b540b0b0b0bâ€¦
<<< a50e02000000

>>> a53d0038000000000b0b0b0b0b0b0b540b0b0b0907480b540b0b0b0b0b0b0b540b0b0b0bâ€¦
<<< a50e02000000
```

1. Its using the SEND_KEY_CMD_V26 instead of SEND_KEY_CMD_V24
2. The checksum is clearly 0x0b (easy to see with all the 0x00s being written).  Based on the read config, if we used four bytes for the checksum it would be (0xbb+0x4e+0xb8+0x44)%256 == 0x05.  Using all eight bytes gives (0xbb+0x4e+0xb8+0x44+0x00+0x00+0x73+0x93)%256 == 0x0b.

**Comment by Maksons** [comment]
@karlp  Please check my coment about check sum calculation length dependence in #21

**Comment by Pe3ucTop** [comment]
@karlp  Please check my comment about check sum calculation length dependence in #20

**Comment by karlp** [comment]
Will do.  I'm also going to recheck with the ch32v307 board, but I ran out of time last night.    It's failing immediately, not in the verify stage, but I really ran out of time.  I managed to flash it using the wch-link and the binary openocd in the MounRiver toolkit.

**Comment by Pe3ucTop** [comment]
@pablomarx  and @karlp please give a try for #21 
I will add all mentioned boot loader versions to my code as well and possibly dummy write.
File size check (compare with device size) is a good idea too which i plan to apply.
My code should be fully working now, and was not finished(reworked) only 1 function (2 old)  it is "end" with or without resetting of chip. Because of limit of time that evening, as well :)

**Comment by arturo182** [comment]
Hi, thanks for all the work! 

I was bringing up my CH32V307 board and was very happy to find this PR here. 

I managed to get the PR to work with my board, but had to make two changes:
I'm using the 64-pin version of the V307 - the CH32V307RCT6. I'm not sure if the 100-pin version is different, but for me, the chip id returned is `0x71`, so the script was wrongly identifying my board as `CH571`, after changing the chip id in lines 54 and 229, I managed to flash and verify the chip! 

In case it's relevant, the bootloader version on my chip is also V2.60

**Comment by Pe3ucTop** [comment]
@arturo182  it's nice to hear and could you do small favor:
- Could you try pull request #21 and report which "chip subid" it will show.
Unfortunately it will probably detect your board as CH571 too, it is because some chips do not have unique ChipId (I found 4 such pairs) and even nor equal to chipid in original file (your case). I'm trying to make more complicated chip identification algorithm based on known data and reverse engineered WCHISP .  
Your reported ChipSubId could help me to figure out such cases. 
Pairs I found with same chipid :
CH32F203 / CH32V303 chipid: 48 (0x30)
CH32F103 / CH32V103 chipid: 50 (0x32)
CH32F205 / CH32V305 chipid: 80 (0x50)
CH32F207 / CH32V307 chipid: 112 (0x70) !! But your report CH32V307 got chipid 113 (0x71) and it is one more new problem.

**Comment by arturo182** [comment]
Thanks, I will check it out later today and let you know.

BTW I'm a part of an unofficial WCH Discord server that also has a WCH employee there, in case you want to ask questions. Here's the server: https://discord.gg/2prGQmA3ez

And here's a note from him regarding this issue:
Screenshot_20220412-100401~2

(UUID is the chk_sum)

**Comment by arturo182** [comment]
For posterity:
image

**Comment by karlp** [comment]
@arturo182 I got stuff working here, but @Pe3ucTop 's branch has more and goes further, it's more likely to be the "future" code at least

**Comment by arturo182** [comment]
I see, I thought this one was more relevant because it was newer. But I'll check out that one then :)

**Comment by karlp** [comment]
It's only newer by a couple of days iirc, and the other person seems to be more motivated in adding all the rest of it, I was just poking this enough to try and get things running :)  I needed some other parts that their branch didn't address, but it's now been updated as the superset of all.

**Pull request merged**
